### ISSUE TITLE
can't fork this example to private repo

### ISSUE THREAD

**Issue by pancho-villa** [buildbot/buildbot-docker-example-config#1]
Hello,

I have a private repo and I can't find a way to fork this repo to setup the master.cfg. If I fork this repo then my config will be world readable. Can I setup a config variable or some way to keep my master.cfg private and not open on github?

Thanks

**Comment by tomprince** [comment]
You can't fork public repos on github privately, but you can create a private repository and push whatever you want there (including a copy of this repository).

**Comment by pancho-villa** [comment]
Ah, of course! Thanks for the heads up!
