### ISSUE TITLE
Restarting worker fails

### ISSUE THREAD

**Issue by pc-tradelab** [buildbot/buildbot-docker-example-config#13]
Hello,

when my docker-compose is not shutdown gracefully, the buildbot-worker cannot restart : ( "Another twistd server is running, PID 5" "simple_worker_1 exited with code 1" ).

To reproduce : 
 - start a simple docker-example-config : #docker-compose up
- check the UI works and the worker is started
- force  shutdown with a double Ctrl-C
- start again : #docker-compose up
- I have an error on my worker container : 
worker_1    | Another twistd server is running, PID 5
worker_1    | 
worker_1    | This could either be a previously started instance of your application or a
worker_1    | different application entirely. To start a new one, either run it in some other
worker_1    | directory, or use the --pidfile and --logfile parameters to avoid clashes.
worker_1    | 
simple_worker_1 exited with code 1

To clean : 
- find the id of the worker container  : # docker ps -a | grep buildbot-worker
- rm this container : # docker rm 75f48fd8c417
- start again : #docker-compose up 
- it works again

Remark : 
-  Apparently even when shutdown gracefully,  I have the same problem

Thanks  !

**Comment by seankelly** [comment]
Is there a volume associated with the container that persists between `docker-compose up`?

**Comment by pc-tradelab** [comment]
no, I use the Compose file of the "simple" folder. It has no volume declared.

**Comment by tardyp** [comment]
The container itself persists between runs if you use docker-compose. A crashed container will restart with the same filesystem so the twisted.pid will stay. As the PID is the same compared to previous run, the worker is fooled thinking the old one is not really dead.

Normally with docker, you would run with --nodaemon, which does not use pidfile. Actually the dockerfile use twistd -ny, we should add the option to disable the pidfile: '--pidfile='
